name: On Pull Request Merge
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Install Rush
        run: node common/scripts/install-run-rush.js install
      - name: Rush Build
        run: node common/scripts/install-run-rush.js build
      - name: Rush Publish
        run: node common/scripts/install-run-rush.js publish --apply --publish --npm-auth-token ${{ secrets.NPM_AUTH_TOKEN }} --add-commit-details --set-access-level public
      - name: Commit New Version & Changelogs
        uses: EndBug/add-and-commit@v7
        with:
          message: "Bump versions & add changelogs"
