name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Fetch latest commit of all branches
        run: git fetch origin main
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
      - name: Check Changelog
        run: node common/scripts/install-run-rush.js change -v --no-fetch
      - name: Install Rush
        run: rush install
      - name: Run Tests
        run: rush test
