name: Test
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        run:
          - git fetch --no-tags --depth=1 origin main
          - git checkout -b main
          - git checkout ${{ github.event.pull_request.head.sha }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.3"
      - name: Check Changelog
        run: node common/scripts/install-run-rush.js change -b main -v --no-fetch
      - name: Install Rush
        run: rush install
      - name: Run Tests
        run: rush test
